"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from .version import __version__ as APP_VERSION

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# Base directory of the project (e.g., Dwarfs4MOSAIC/src)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# === Security ===

# SECURITY WARNING: Never expose this secret key in production!
SECRET_KEY = 'django-insecure-!y*cdqk2#drd&j)0dc9%5$&(6306#+q26d&rcv-l7_mypph_pk'

# SECURITY WARNING: Turn off debug in production!
DEBUG = True

# Allowed domains to serve the app (empty during development)
ALLOWED_HOSTS = []


# === Installed Applications ===

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dwarfs4MOSAIC.apps.Dwarfs4MOSAICConfig',
]

# === Middleware Stack ===

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# === URL Configuration ===

ROOT_URLCONF = 'dwarfs4MOSAIC_website.urls'

# === Templates ===

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'dwarfs4MOSAIC' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'dwarfs4MOSAIC_website.context_processors.app_version'
            ],
        },
    },
]

# === WSGI ===

WSGI_APPLICATION = 'dwarfs4MOSAIC_website.wsgi.application'

# === Database ===

# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# === Password Validation ===

# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# === Internationalization ===

# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# === Static Files (CSS, JS, Images) ===

# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "dwarfs4MOSAIC" / "static"]

# === Default Primary Key Field Type ===

# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === Session Settings ===

#SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# Idle time before session expires
SESSION_COOKIE_AGE = 900  # Session timeout in seconds (15 minutes)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Session expires when the browser is closed
SESSION_SAVE_EVERY_REQUEST = True # Save the session on every request

# Optional security settings:
#SESSION_COOKIE_NAME = 'sessionid'
#SESSION_COOKIE_HTTPONLY = True
#SESSION_COOKIE_SECURE = False  # Change to True if using HTTPS
#SESSION_COOKIE_SAMESITE = 'Lax'

# === Media Files ===

MEDIA_URL = '/media/' # URL to serve media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Filesystem path where uploaded media files are stored

# === Authentication Redirects ===

LOGIN_URL = '/admin/login'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/home/'