# Generated by Django 5.1.5 on 2025-03-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='observatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Observatory',
                'verbose_name_plural': 'Observatories',
            },
        ),
        migrations.CreateModel(
            name='telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('obs_tel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarfs4MOSAIC.observatory')),
            ],
            options={
                'verbose_name': 'Telescope',
                'verbose_name_plural': 'Telescopes',
            },
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tel_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarfs4MOSAIC.telescope')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
    ]
