# Generated by Django 5.1.5 on 2025-03-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_observatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Observatory',
                'verbose_name_plural': 'Observatories',
            },
        ),
        migrations.CreateModel(
            name='Tbl_telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('obs_tel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarfs4MOSAIC.tbl_observatory')),
            ],
            options={
                'verbose_name': 'Telescope',
                'verbose_name_plural': 'Telescopes',
            },
        ),
        migrations.CreateModel(
            name='Tbl_instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('tel_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarfs4MOSAIC.tbl_telescope')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
    ]
