# Generated by Django 5.1.5 on 2025-03-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observatory',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='tel_ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarfs4MOSAIC.tbl_telescope', verbose_name='Telescope'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='obs_tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarfs4MOSAIC.tbl_observatory', verbose_name='Observatory'),
        ),
    ]
