# Generated by Django 5.1.5 on 2025-03-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0002_tbl_observatory_location_alter_tbl_instrument_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observatory',
            name='coordinates',
            field=models.JSONField(default=dict),
        ),
    ]
