# Generated by Django 5.1.5 on 2025-03-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0005_tbl_observatory_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observatory',
            name='website',
            field=models.URLField(default='', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude [m]'),
        ),
    ]
