# Generated by Django 5.1.5 on 2025-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0006_tbl_observatory_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_telescope',
            name='website',
            field=models.URLField(default='', verbose_name='Website'),
        ),
    ]
