# Generated by Django 5.1.5 on 2025-03-12 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0007_tbl_telescope_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_telescope',
            name='aperture',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aperture [cm]'),
        ),
        migrations.AddField(
            model_name='tbl_telescope',
            name='owner',
            field=models.CharField(default='', max_length=200, verbose_name='Institutional Owner'),
        ),
        migrations.AddField(
            model_name='tbl_telescope',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('operational', 'Operational'), ('inoperative', 'Inoperative'), ('maintenance', 'Under Maintenance')], default='unknown', max_length=20, verbose_name='Status'),
        ),
    ]
