# Generated by Django 5.1.5 on 2025-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0008_tbl_telescope_aperture_tbl_telescope_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_telescope',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institutional Owner'),
        ),
    ]
