# Generated by Django 5.1.5 on 2025-03-12 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0009_alter_tbl_telescope_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_telescope',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fullname'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='aperture',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aperture (m)'),
        ),
    ]
