# Generated by Django 5.1.5 on 2025-03-12 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0010_tbl_telescope_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_instrument',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fullname'),
        ),
        migrations.AddField(
            model_name='tbl_instrument',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('operational', 'Operational'), ('inoperative', 'Inoperative'), ('maintenance', 'Under Maintenance')], default='unknown', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='tbl_instrument',
            name='website',
            field=models.URLField(default='', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='aperture',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aperture (m)'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='owner',
            field=models.CharField(default='', max_length=200, verbose_name='Institutional Owner'),
        ),
    ]
