# Generated by Django 5.1.5 on 2025-03-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0011_tbl_instrument_fullname_tbl_instrument_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'User'), ('stuff', 'Stuff')], default='user', max_length=50, verbose_name='Role')),
                ('institution', models.CharField(default='', max_length=200, verbose_name='Institution')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_instrument',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='tbl_telescope',
            name='fullname',
        ),
        migrations.AddField(
            model_name='tbl_instrument',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tbl_telescope',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
    ]
