# Generated by Django 5.1.5 on 2025-03-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0012_tbl_member_remove_tbl_instrument_fullname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.CreateModel(
            name='Tbl_observing_run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Seeing in arcseconds', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_observing_runs', to='dwarfs4MOSAIC.tbl_member', verbose_name='Leader')),
            ],
            options={
                'verbose_name': 'Observing Run',
                'verbose_name_plural': 'Observing Runs',
            },
        ),
    ]
