# Generated by Django 5.1.5 on 2025-03-13 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0013_alter_tbl_member_options_tbl_observing_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_observatory',
            name='altitude',
            field=models.FloatField(blank=True, help_text='Altitude in meters', null=True, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_run',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='aperture',
            field=models.FloatField(default=0, help_text='Aperture in meters', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aperture'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='owner',
            field=models.TextField(default='', verbose_name='Institutional Owner'),
        ),
        migrations.CreateModel(
            name='Tbl_observing_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('observation_mode', models.CharField(choices=[('photometry', 'Photometry'), ('spectroscopy', 'Spectroscopy'), ('imaging', 'Imaging')], default='photometry', max_length=50, verbose_name='Observation Mode')),
                ('filters', models.CharField(blank=True, max_length=100, null=True, verbose_name='Filters')),
                ('exposure_time', models.DurationField(blank=True, null=True, verbose_name='Exposure Time')),
                ('seeing', models.FloatField(blank=True, help_text='Seeing in arcseconds', null=True, verbose_name='Seeing')),
                ('weather_conditions', models.TextField(blank=True, null=True, verbose_name='Weather Conditions')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dwarfs4MOSAIC.tbl_instrument', verbose_name='Instument')),
            ],
            options={
                'verbose_name': 'Observing Block',
                'verbose_name_plural': 'Observing Block',
            },
        ),
    ]
