# Generated by Django 5.1.5 on 2025-03-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0014_alter_tbl_observatory_altitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_observing_block',
            options={'verbose_name': 'Observing Block', 'verbose_name_plural': 'Observing Blocks'},
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='tel_ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dwarfs4MOSAIC.tbl_telescope', verbose_name='Telescope'),
        ),
        migrations.AlterField(
            model_name='tbl_member',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'User'), ('stuff', 'Staff')], default='user', max_length=50, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='exposure_time',
            field=models.DurationField(blank=True, help_text='Exposure time in seconds', null=True, verbose_name='Exposure Time'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='observation_mode',
            field=models.CharField(choices=[('photometry', 'Photometry'), ('spectroscopy', 'Spectroscopy'), ('imaging', 'Imaging')], max_length=50, verbose_name='Observation Mode'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='obs_tel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dwarfs4MOSAIC.tbl_observatory', verbose_name='Observatory'),
        ),
    ]
