# Generated by Django 5.1.5 on 2025-03-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0015_alter_tbl_observing_block_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observing_block',
            name='obs_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dwarfs4MOSAIC.tbl_observing_run', verbose_name='Observatory'),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='tel_ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dwarfs4MOSAIC.tbl_telescope', verbose_name='Telescope'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dwarfs4MOSAIC.tbl_instrument', verbose_name='Instument'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_run',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='led_observing_runs', to='dwarfs4MOSAIC.tbl_member', verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='obs_tel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dwarfs4MOSAIC.tbl_observatory', verbose_name='Observatory'),
        ),
    ]
