# Generated by Django 5.1.5 on 2025-03-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0016_tbl_observing_block_obs_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'User'), ('core', 'Core')], default='user', max_length=50, verbose_name='Role')),
                ('institution', models.CharField(default='', max_length=200, verbose_name='Institution')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Researcher',
                'verbose_name_plural': 'Researchers',
            },
        ),
        migrations.RemoveField(
            model_name='tbl_observing_run',
            name='leader',
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dwarfs4MOSAIC.tbl_instrument', verbose_name='Instrument'),
        ),
        migrations.DeleteModel(
            name='Tbl_member',
        ),
    ]
