# Generated by Django 5.1.5 on 2025-03-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0017_tbl_researcher_remove_tbl_observing_run_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_observing_block',
            name='instrument',
        ),
        migrations.AddField(
            model_name='tbl_observing_run',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dwarfs4MOSAIC.tbl_instrument', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='obs_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dwarfs4MOSAIC.tbl_observing_run', verbose_name='Observing Run'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('core', 'Core')], default='user', max_length=50, verbose_name='Role'),
        ),
    ]
