# Generated by Django 5.1.5 on 2025-03-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0018_remove_tbl_observing_block_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observing_run',
            name='researches',
            field=models.ManyToManyField(related_name='observing_runs', to='dwarfs4MOSAIC.tbl_researcher'),
        ),
    ]
