# Generated by Django 5.1.5 on 2025-03-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0019_tbl_observing_run_researches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_observing_run',
            old_name='researches',
            new_name='researchers',
        ),
    ]
