# Generated by Django 5.1.5 on 2025-03-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0020_rename_researches_tbl_observing_run_researchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observing_block',
            name='researchers',
            field=models.ManyToManyField(related_name='observing_blocks', to='dwarfs4MOSAIC.tbl_researcher'),
        ),
    ]
