# Generated by Django 5.1.5 on 2025-03-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0021_tbl_observing_block_researchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_observatory',
            name='altitude',
            field=models.FloatField(blank=True, help_text='meters', null=True, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
    ]
