# Generated by Django 5.1.5 on 2025-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0023_remove_tbl_observing_block_researchers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('type', models.CharField(choices=[('star', 'Star'), ('galaxy', 'Galaxy'), ('nebula', 'Nebula'), ('cluster', 'Star Cluster'), ('exoplanet', 'Exoplanet'), ('other', 'Other')], max_length=50, verbose_name='Type')),
                ('right_ascension', models.FloatField(blank=True, help_text='HH:MM:SS', null=True, verbose_name='Right Ascension')),
                ('declination', models.FloatField(blank=True, help_text='+/- deg:min:sec', null=True, verbose_name='Declination')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='Magnitude')),
                ('redshift', models.FloatField(blank=True, null=True, verbose_name='Redshift (z)')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (pc)')),
                ('size', models.FloatField(blank=True, help_text='arcmin', null=True, verbose_name='Size')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
            },
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='exposure_time',
            field=models.DurationField(blank=True, help_text='seconds', null=True, verbose_name='Exposure Time'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='seeing',
            field=models.FloatField(blank=True, help_text='arcseconds', null=True, verbose_name='Seeing'),
        ),
    ]
