# Generated by Django 5.1.5 on 2025-03-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0025_tbl_observing_block_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_target',
            name='distance',
        ),
        migrations.AddField(
            model_name='tbl_target',
            name='semester',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='first', max_length=6, verbose_name='Semester of observation'),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('operational', 'Operational'), ('inoperative', 'Inoperative'), ('maintenance', 'Under Maintenance')], default='unknown', max_length=11, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='observation_mode',
            field=models.CharField(choices=[('photometry', 'Photometry'), ('spectroscopy', 'Spectroscopy'), ('imaging', 'Imaging')], default='photometry', max_length=12, verbose_name='Observation Mode'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='role',
            field=models.CharField(choices=[('core', 'Core Team'), ('collaborator', 'Collaborator')], default='core', max_length=12, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='size',
            field=models.FloatField(blank=True, help_text='arcsec', null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='type',
            field=models.CharField(choices=[('star', 'Star'), ('galaxy', 'Galaxy'), ('nebula', 'Nebula'), ('cluster', 'Star Cluster'), ('exoplanet', 'Exoplanet'), ('other', 'Other')], default='galaxy', max_length=9, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('operational', 'Operational'), ('inoperative', 'Inoperative'), ('maintenance', 'Under Maintenance')], default='unknown', max_length=11, verbose_name='Status'),
        ),
    ]
