# Generated by Django 5.1.5 on 2025-03-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0027_remove_tbl_observing_block_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_target',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='semester',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second')], default='first', max_length=6, verbose_name='Visibility semester'),
        ),
    ]
