# Generated by Django 5.1.5 on 2025-03-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0028_tbl_target_image_alter_tbl_target_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_target',
            name='semester',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('both', 'Both')], default='first', max_length=6, verbose_name='Visibility semester'),
        ),
    ]
