# Generated by Django 5.1.5 on 2025-03-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0030_alter_tbl_researcher_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tbl_researcher',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='username',
        ),
        migrations.AddField(
            model_name='tbl_researcher',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='tbl_researcher',
            name='role',
            field=models.CharField(choices=[('core', 'Core Team'), ('collaborator', 'Collaborator')], default='core', max_length=12, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='institution',
            field=models.CharField(default='', max_length=200, verbose_name='Institution'),
        ),
    ]
