# Generated by Django 5.1.5 on 2025-03-30 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0033_alter_tbl_researcher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='role',
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchers', to=settings.AUTH_USER_MODEL, verbose_name='User name'),
        ),
    ]
