# Generated by Django 5.1.5 on 2025-04-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0035_alter_tbl_researcher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_researcher',
            name='is_phd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='semester',
            field=models.CharField(max_length=10, verbose_name='Visibility semester'),
        ),
    ]
