# Generated by Django 5.1.5 on 2025-04-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0036_tbl_researcher_is_phd_alter_tbl_target_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_researcher',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='is_phd',
            field=models.BooleanField(default=False, verbose_name='Is PhD'),
        ),
    ]
