# Generated by Django 5.1.5 on 2025-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0037_tbl_researcher_comments_alter_tbl_researcher_is_phd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_instrument',
            options={'ordering': ['name'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
        migrations.AlterModelOptions(
            name='tbl_observatory',
            options={'ordering': ['name'], 'verbose_name': 'Observatory', 'verbose_name_plural': 'Observatories'},
        ),
        migrations.AlterModelOptions(
            name='tbl_observing_block',
            options={'ordering': ['start_time'], 'verbose_name': 'Observing Block', 'verbose_name_plural': 'Observing Blocks'},
        ),
        migrations.AlterModelOptions(
            name='tbl_observing_run',
            options={'ordering': ['start_date'], 'verbose_name': 'Observing Run', 'verbose_name_plural': 'Observing Runs'},
        ),
        migrations.AlterModelOptions(
            name='tbl_researcher',
            options={'ordering': ['user__username'], 'verbose_name': 'Researcher', 'verbose_name_plural': 'Researchers'},
        ),
        migrations.AlterModelOptions(
            name='tbl_target',
            options={'ordering': ['name'], 'verbose_name': 'Target', 'verbose_name_plural': 'Targets'},
        ),
        migrations.AlterModelOptions(
            name='tbl_telescope',
            options={'ordering': ['name'], 'verbose_name': 'Telescope', 'verbose_name_plural': 'Telescopes'},
        ),
        migrations.AddField(
            model_name='tbl_target',
            name='file_path',
            field=models.FileField(blank=True, upload_to='datafiles/', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
    ]
