# Generated by Django 5.1.5 on 2025-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0038_alter_tbl_instrument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_target',
            name='file_path',
        ),
        migrations.AddField(
            model_name='tbl_target',
            name='datafiles_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Data files path'),
        ),
    ]
