# Generated by Django 5.1.5 on 2025-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0039_remove_tbl_target_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_target',
            name='datafiles_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data files path'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image path'),
        ),
    ]
