# Generated by Django 5.1.5 on 2025-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0041_tbl_researcher_email_tbl_researcher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='seeing',
            field=models.FloatField(blank=True, help_text='arcsec', null=True, verbose_name='Seeing'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='website',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Website'),
        ),
    ]
