# Generated by Django 5.1.5 on 2025-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0043_tbl_researcher_allowed_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_researcher',
            name='allowed_target',
            field=models.ManyToManyField(related_name='allowed_researchers', to='dwarfs4MOSAIC.tbl_target'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='allowed_blocks',
            field=models.ManyToManyField(related_name='allowed_researchers', to='dwarfs4MOSAIC.tbl_observing_block'),
        ),
    ]
