# Generated by Django 5.1.5 on 2025-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0045_rename_allowed_target_tbl_researcher_allowed_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='allowed_targets',
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='observing_blocks', to='dwarfs4MOSAIC.tbl_target'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_run',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='observing_runs', to='dwarfs4MOSAIC.tbl_researcher'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='allowed_blocks',
            field=models.ManyToManyField(blank=True, related_name='allowed_researchers', to='dwarfs4MOSAIC.tbl_observing_block'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='type',
            field=models.CharField(choices=[('galaxy', 'Galaxy'), ('calibration', 'Calibration'), ('other', 'Other')], default='galaxy', max_length=20, verbose_name='Type'),
        ),
    ]
