# Generated by Django 5.1.5 on 2025-07-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0047_tbl_observing_block_allowed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_researcher',
            name='allowed_blocks',
        ),
    ]
