# Generated by Django 5.1.5 on 2025-07-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0048_remove_tbl_researcher_allowed_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_researcher',
            name='role',
            field=models.CharField(choices=[('core_team', 'Core Team'), ('collaborator', 'Collaborator')], default='core_team', max_length=15, null=True, verbose_name='Role'),
        ),
    ]
