# Generated by Django 5.1.5 on 2025-07-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0049_tbl_researcher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_researcher',
            name='role',
            field=models.CharField(choices=[('core_team', 'Core Team'), ('collaborator', 'Collaborator')], default='core_team', max_length=15, verbose_name='Role'),
        ),
    ]
