# Generated by Django 5.1.5 on 2025-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0050_alter_tbl_researcher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_researcher',
            name='denied_blocks',
            field=models.ManyToManyField(blank=True, related_name='denied_researchers', to='dwarfs4MOSAIC.tbl_observing_block'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='role',
            field=models.CharField(choices=[('core_team', 'Core Team'), ('collaborator', 'Collaborator')], default='collaborator', max_length=15, verbose_name='Role'),
        ),
    ]
