# Generated by Django 5.1.5 on 2025-10-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0051_tbl_researcher_denied_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observing_block',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Observation semester'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='target',
            field=models.ManyToManyField(blank=True, help_text='Targets that belong to the block.', related_name='observing_blocks', to='dwarfs4MOSAIC.tbl_target'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_run',
            name='researchers',
            field=models.ManyToManyField(blank=True, help_text='Researchers who participated in the observing run.', related_name='observing_runs', to='dwarfs4MOSAIC.tbl_researcher'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='denied_blocks',
            field=models.ManyToManyField(blank=True, help_text='The user does not have authorized access to these blocks (even if they belong to a group that does have authorized access). ', related_name='denied_researchers', to='dwarfs4MOSAIC.tbl_observing_block'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='redshift',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Redshift (z)'),
        ),
    ]
