# Generated by Django 5.1.5 on 2025-10-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0052_tbl_observing_block_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_instrument',
            name='configuration',
            field=models.TextField(blank=True, help_text="Comma-separated list of configurations, e.g., 'Mode1,Mode2,Mode3'"),
        ),
        migrations.AddField(
            model_name='tbl_instrument',
            name='filters',
            field=models.TextField(blank=True, help_text='Comma-separated list of filters'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Observing semester'),
        ),
    ]
