# Generated by Django 5.1.5 on 2025-10-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0053_tbl_instrument_configuration_tbl_instrument_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_observing_block',
            name='configuration',
            field=models.CharField(blank=True, help_text='Instrument configuration', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='configuration',
            field=models.TextField(blank=True, help_text='Comma-separated', verbose_name='Configurations'),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='filters',
            field=models.TextField(blank=True, help_text='Comma-separated'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='filters',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instrument filter'),
        ),
    ]
