# Generated by Django 5.1.5 on 2025-10-19 09:50

import django.core.validators
import dwarfs4MOSAIC.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0054_tbl_observing_block_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_observatory',
            name='latitude',
            field=models.CharField(blank=True, help_text='DD:MM:SS', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_latitude], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='longitude',
            field=models.CharField(blank=True, help_text='DD:MM:SS', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_longitude], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='configuration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instrument configuration'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='exposure_time',
            field=models.DurationField(blank=True, help_text='seconds', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Exposure Time'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='seeing',
            field=models.FloatField(blank=True, help_text='arcsec', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seeing'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='declination',
            field=models.CharField(blank=True, help_text='+/- deg:min:sec', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_declination], verbose_name='Declination'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='right_ascension',
            field=models.CharField(blank=True, help_text='HH:MM:SS', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_right_ascension], verbose_name='Right Ascension'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='size',
            field=models.FloatField(blank=True, help_text='arcsec', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Size'),
        ),
    ]
