# Generated by Django 6.0.5 on 2026-05-13 19:04

import dwarfs4MOSAIC.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0055_alter_tbl_observatory_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_observatory',
            name='latitude',
            field=models.CharField(blank=True, help_text='DD:MM:SS[.sss][N/S]', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_latitude], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='longitude',
            field=models.CharField(blank=True, help_text='DDD:MM:SS[.sss][E/W]', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_longitude], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='declination',
            field=models.CharField(blank=True, help_text='±DD:MM:SS[.sss]', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_declination], verbose_name='Declination'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='redshift',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Redshift (z)'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='right_ascension',
            field=models.CharField(blank=True, help_text='HH:MM:SS[.sss]', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_right_ascension], verbose_name='Right Ascension'),
        ),
    ]
