# Generated by Django 6.0.5 on 2026-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0056_alter_tbl_observatory_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_target',
            name='website',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='magnitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Magnitude (r AB)'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='redshift',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Redshift (z)'),
        ),
    ]
