# Generated by Django 6.0.5 on 2026-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0057_tbl_target_website_alter_tbl_target_magnitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_target',
            name='redshift_error',
            field=models.FloatField(blank=True, null=True, verbose_name='Redshift error'),
        ),
        migrations.AddField(
            model_name='tbl_target',
            name='redshift_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Redshift value (z)'),
        ),
    ]
