# Generated by Django 6.0.5 on 2026-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0058_tbl_target_redshift_error_tbl_target_redshift_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_target',
            name='redshift',
        ),
    ]
