# Generated by Django 6.0.5 on 2026-05-27 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0059_remove_tbl_target_redshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_target',
            name='magnitude',
            field=models.FloatField(blank=True, help_text='r band (AB system)', null=True, verbose_name='Magnitude'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Visibility semester'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='size',
            field=models.FloatField(blank=True, help_text='arcsec', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Angular size'),
        ),
    ]
