# Generated by Django 6.0.5 on 2026-05-29 17:17

import django.core.validators
import dwarfs4MOSAIC.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0060_alter_tbl_target_magnitude_alter_tbl_target_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_instrument',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tbl_instrument',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='longitude',
            field=models.CharField(blank=True, help_text='DDD:MM:SS[.sss][E/W]', max_length=15, null=True, validators=[dwarfs4MOSAIC.validators.validate_longitude], verbose_name=' Longitude'),
        ),
        migrations.AlterField(
            model_name='tbl_observatory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='configuration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrument configuration'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='exposure_time',
            field=models.FloatField(blank=True, help_text='seconds', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Exposure Time'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='filters',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrument filter'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observing semester'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_block',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_run',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_observing_run',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='tbl_researcher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='declination',
            field=models.CharField(default='', help_text='±DD:MM:SS[.sss]', max_length=15, validators=[dwarfs4MOSAIC.validators.validate_declination], verbose_name='Declination'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_target',
            name='right_ascension',
            field=models.CharField(default='', help_text='HH:MM:SS[.sss]', max_length=15, validators=[dwarfs4MOSAIC.validators.validate_right_ascension], verbose_name='Right Ascension'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='aperture',
            field=models.FloatField(blank=True, default=0, help_text='meters', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aperture'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tbl_telescope',
            name='owner',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Institutional Owner'),
        ),
    ]
