# Generated by Django 6.0.5 on 2026-05-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwarfs4MOSAIC', '0061_alter_tbl_instrument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_target',
            name='declination_deg',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tbl_target',
            name='right_ascension_hours',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
